### ISSUE TITLE
It seems that it can not install with the new Ionic 3.0 cli.

### ISSUE THREAD

**Issue by MCerk** [darryncampbell/darryncampbell-cordova-plugin-intent#1]

**Comment by darryncampbell** [comment]
Strange, yes for me `ionic cordova plugin add https://github.com/darryncampbell/darr
yncampbell-cordova-plugin-intent.git` fails but `cordova plugin add https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent.git` succeeds.  You might also want to use `ionic cordova plugin add com-darryncampbell-cordova-plugin-intent` which will get the plugin from npmjs

I'm not sure on the root cause, I'm getting errors about a remote helper for 'https' so I guess there is a package missing somewhere.
