### ISSUE TITLE
with ionic 4+ when app is closed the onIntent is callback is not triggered

### ISSUE THREAD

**Issue by shamis** [darryncampbell/darryncampbell-cordova-plugin-intent#121]
When the app is running in the background everything is working as expected.

```javascript
this.webIntent.onIntent().subscribe((intent: { extras: any; }) => {
     console.log('Received Intent: ' + JSON.stringify(intent.extras));
     alert('Received Intent: ' + JSON.stringify(intent.extras));
});
```

The above code is placed inside platform ready. 

Not able to retrieve the extras when the app is closed

**Comment by darryncampbell** [comment]
Hi, does subscribe register a broadcast receiver?  Although this plugin is listed as the implementation for webIntent I didn't actually write any of the code for the webIntent API.  

Closing the app will cause Android to unregister any existing dynamic broadcast receivers so this is expected behaviour if I have correctly understood the question.

**Comment by shamis** [comment]
thanks for the quick response, I had not registered a brodcast receiver just using the package name to startActivity with extras. It works well when the app is in the background. Have not found a way to make it work when the app is closed.

**Comment by darryncampbell** [comment]
Perhaps the subscription is getting cleared when you close the app? https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/web-intent/index.ts#L215

**Comment by shamis** [comment]
I was able to use **getIntent** when the app was closed. Sorry didnt notice that at first. Thanks for the help.
