### ISSUE TITLE
realPathFromUri

### ISSUE THREAD

**Issue by akinzeman** [darryncampbell/darryncampbell-cordova-plugin-intent#95]
I successfully get uri of clipItems, however, realPathFromUri function not works (neither success nor error functions thrown anything)
do i miss sth?

intent = {	"clipItems": [ {   "uri": "content://0@media/external/images/media/56684",
						"type": "image/jpeg",
						"extension": "jpg" 
				    } ]
             }

var uri = intent.clipItems[0].uri; 
window.plugins.intentShim.realPathFromUri( uri, function (realPath) {                            
           alert( realPath ); //not worked!
          }
  , function () {  alert('Error realPath from media_uri');  } ); //also error not thrown!

**Comment by darryncampbell** [comment]
Is this on Android 10? I wonder if it could be related to scoped storage somehow.

**Comment by akinzeman** [comment]
Android 6.0.1

**Comment by darryncampbell** [comment]
There is a sample at https://github.com/darryncampbell/plugin-intent-api-exerciser/blob/master/www/js/index.js#L188.  Did you grant READ_EXTERNAL_STORAGE permission?  This function requires that permission.

**Comment by HarelM** [comment]
It this method unofficial? I didn't see it in the documentation or as part of Ionic wrapper.

**Comment by darryncampbell** [comment]
@HarelM this method was not documented due to laziness

Moving forward I'm concerned about the implications of Android scoped storage & I would probably have to rework this functionality for things like the media use case mentioned in this issue.  

But, due to time constraints I am unlikely to make those kind of big changes at this stage.

**Comment by HarelM** [comment]
Thanks for getting back to me so quickly!
Yes, I agree, I'm concerned about it too.
I have switched my entire app usage to work with sharing of files created in memory instead of using the file system.
I also migrated from open-with pluging that was handling my intents for this plugin to reduce complexity in iOS so I'm comparing the code there to stuff I need to do in js now.
The only thing I wasn't getting right was getting an image name when I share an image with my app, so I'm guessing this method should do it, but I'm concerned about android 11 as well.
Let me know if and how I can help.
